title: cvless
description: Jekyll theme for a beautiful online CV
baseurl: ""
url: https://piazzai.github.io/cvless

theme: cvless

# site settings
taglong: Jekyll theme for a beautiful online CV
tagshort: Jekyll theme

# author settings
author:
  name: Felix Aertebjerg
  email: aertebjerg.felix@gmail.com
photo: assets/files/photo.jpg
address: Pladehals Alle 53, 2450 Copenhagen
phone: +45 61486669

# social media links
social:
  github: aerte
  linkedin: felix-aertebjerg

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
